# Generated by Django 4.1.7 on 2023-03-22 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import excel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cancha', models.CharField(max_length=30, verbose_name='Name')),
                ('numeracion', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(help_text='Ingresa datos para agenda', validators=[excel.models.validar_dia])),
                ('horario', models.CharField(choices=[('1', '06:00'), ('2', '07:00'), ('3', '08:00'), ('4', '09:00'), ('5', '10:00')], max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='excel.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('dia', 'horario', 'service')},
            },
        ),
    ]
