# Generated by Django 4.1.7 on 2023-03-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='numeracion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, verbose_name='Cancha'),
        ),
    ]
