# Generated by Django 4.1.7 on 2023-03-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(choices=[('09', '09:00 AM'), ('10', '10:00 AM'), ('11', '11:00 AM'), ('12', '12:00 PM'), ('', ''), ('17', '05:00 PM'), ('18', '06:00 PM'), ('19', '07:00 PM'), ('20', '08:00 PM'), ('21', '09:00 PM'), ('22', '10:00 PM')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='numeracion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, verbose_name='Cancha'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.horario'),
        ),
    ]
